CREATE TABLE Game (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	HOST_TEAM INTEGER NOT NULL,
	GUEST_TEAM INTEGER NOT NULL,
	H_T_SCORE INTEGER NOT NULL,
	G_T_SCORE INTEGER NOT NULL,
	GAME_DATE text NOT NULL
);

CREATE TABLE InjuryRecord (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	PLAYER_ID INTEGER NOT NULL,
	INCI_DESC text NOT NULL,
	INJ_DESC text NOT NULL
);

CREATE TABLE Player (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	TEAM_ID INTEGER NOT NULL,
	NAME text NOT NULL,
	POSITION text NOT NULL,
	SKILL_LEVEL INTEGER NOT NULL,
	SALARY double NOT NULL
);

CREATE TABLE Team (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NAME text NOT NULL,
	CITY text NOT NULL,
	COACH text NOT NULL,
	CAPTAIN text NOT NULL
);

SELECT NAME, SALARY
FROM Player AS P, Team AS T
WHERE  	T.NAME = 'Vegas Golden Knights' AND T.ID = P.TEAM_ID;