CREATE TABLE CUSTOMER (
	CustID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	Name text NOT NULL,
	Phone text NOT NULL
);

CREATE TABLE RENTAL (
	CustID INTEGER PRIMARY KEY NOT NULL,
	VehicleID text PRIMARY KEY NOT NULL,
	StartDate text NOT NULL,
	OrderDate text NOT NULL,
	RentalType INTEGER NOT NULL,
	Qty INTEGER NOT NULL,
	ReturnDate text NOT NULL,
	TotalAmount INTEGER NOT NULL,
	PaymentDate text NOT NULL,
	FOREIGN KEY (CustID) REFERENCES CUSTOMER (CustID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (VehicleID) REFERENCES VEHICLE (VehicleID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE VEHICLE (
	VehicleID tetx PRIMARY KEY NOT NULL,
	Description text NOT NULL,
	Year INTEGER NOT NULL,
	Type INTEGER NOT NULL,
	Category INTEGER NOT NULL,
	FOREIGN KEY (Type) REFERENCES RATE (Type) ON DELETE CASCADE ON UPDATE CASCADE
	FOREIGN KEY (Category) REFERENCES RATE (Category) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE RATE (
	Type INTEGER NOT NULL,
	Category INTEGER NOT NULL,
	Weekly	INTEGER NOT NULL,
	Daily INTEGER NOT NULL
);
