--GROUP MEMBER: CHERRYL MARIA BIBIN, NINAD PANDIT, GIA DAO

-- PART 2: SQL QUERIES - CREATE STATEMENT

-- Create Statement to create the tables for player, team, injuryrecord, game 

CREATE TABLE Game (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	HOST_TEAM INTEGER NOT NULL,
	GUEST_TEAM INTEGER NOT NULL,
	H_T_SCORE INTEGER NOT NULL,
	G_T_SCORE INTEGER NOT NULL,
	GAME_DATE text NOT NULL
);

CREATE TABLE InjuryRecord (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	PLAYER_ID INTEGER NOT NULL,
	INCI_DESC text NOT NULL,
	INJ_DESC text NOT NULL,
	FOREIGN KEY (PLAYER_ID) REFERENCES Player (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Player (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	TEAM_ID INTEGER NOT NULL,
	NAME text NOT NULL,
	POSITION text NOT NULL,
	SKILL_LEVEL INTEGER NOT NULL,
	SALARY double NOT NULL,
	FOREIGN KEY (TEAM_ID) REFERENCES Team (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Team (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NAME text NOT NULL,
	CITY text NOT NULL,
	COACH text NOT NULL,
	CAPTAIN text NOT NULL
);


